AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Reference Pipeline for Education Data Analytics

  SAM Template for auth, API, and back-end resources

Parameters:
  pEnv:
    Type: String
  pEncryptionKey: 
    Type: String
  pImageTag:
    Type: String

Mappings:
  EnvMap:
    dev:
      pVpcName: dev-ai-aloe-vpc
      pOrg: ai-aloe-dev
      pNumAzs: 2
      pCreateNatGateway: true
      pCreateSingleNatGateway: true
      pCidr: 10.1.0.0/20
      pTier1Subnet1Cidr: 10.1.0.0/24
      pTier1Subnet2Cidr: 10.1.1.0/24
      pTier2Subnet1Cidr: 10.1.2.0/24
      pTier2Subnet2Cidr: 10.1.3.0/24
      pNotificationList: abragg@unicon.net
    qa:
      pVpcName: qa-ai-aloe-vpc
      pOrg: ai-aloe-qa
      pNumAzs: 2
      pCreateNatGateway: true
      pCreateSingleNatGateway: true
      pCidr: 10.2.0.0/20
      pTier1Subnet1Cidr: 10.2.0.0/24
      pTier1Subnet2Cidr: 10.2.1.0/24
      pTier2Subnet1Cidr: 10.2.2.0/24
      pTier2Subnet2Cidr: 10.2.3.0/24
      pNotificationList: tcouper@1edtech.org


Resources:

    Auth:
      Type: AWS::Serverless::Application
      Properties:
        Location: cognito/template.yaml
        Parameters:
          SSMPrefix: !Ref AWS::StackName

    API:
      Type: AWS::Serverless::Application
      Properties:
        Location: api/template.yaml
        Parameters:
          CognitoUserPoolArn: !GetAtt Auth.Outputs.CognitoUserPoolArn
          SensitiveDBHost: !GetAtt Backend.Outputs.SensitiveDataDatabaseEndpoint
          SensitiveDBPort: !GetAtt Backend.Outputs.SensitiveDataDatabaseEndpointPort
          SensitiveDBName: !GetAtt Backend.Outputs.SensitiveDataDatabaseDBName
          SensitiveDBIamUser: !GetAtt Backend.Outputs.SensitiveDataDatabaseIamUser
          SensitiveDBSecurityGroup: !GetAtt Backend.Outputs.SensitiveDataDatabaseSecurityGroup
          PublishedDBHost: !GetAtt Backend.Outputs.PublishedDataDatabaseEndpoint
          PublishedDBPort: !GetAtt Backend.Outputs.PublishedDataDatabaseEndpointPort
          PublishedDBName: !GetAtt Backend.Outputs.PublishedDataDatabaseDBName
          PublishedDBIamUser: !GetAtt Backend.Outputs.PublishedDataDatabaseIamUser
          PublishedDBSecurityGroup: !GetAtt Backend.Outputs.PublishedDataDatabaseSecurityGroup
          PrivateSubnets: !GetAtt Backend.Outputs.PrivateSubnets
          EncryptionKey: !Ref pEncryptionKey

    Backend:
      Type: AWS::Serverless::Application
      Properties:
        Location: backend/template.yaml
        Parameters:
          pEnv: !Ref pEnv
          pVpcName: !FindInMap [EnvMap, !Ref pEnv, pVpcName]
          pOrg: !FindInMap [EnvMap, !Ref pEnv, pOrg]
          pNumAzs: !FindInMap [EnvMap, !Ref pEnv, pNumAzs]
          pCreateNatGateway: !FindInMap [EnvMap, !Ref pEnv, pCreateNatGateway]
          pCidr: !FindInMap [EnvMap, !Ref pEnv, pCidr]
          pTier1Subnet1Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier1Subnet1Cidr]
          pTier1Subnet2Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier1Subnet2Cidr]
          pTier2Subnet1Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier2Subnet1Cidr]
          pTier2Subnet2Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier2Subnet2Cidr]
          pNotificationList: !FindInMap [EnvMap, !Ref pEnv, pNotificationList]
          pImageTag: !Ref pImageTag

Outputs:

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt API.Outputs.AnalyticsApiEndpoint
