AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Reference Pipeline for Education Data Analytics

  SAM Template for auth, API, and back-end resources

Parameters:
  pEnv:
    Type: String
  pEncryptionKey: 
    Type: String
  pImageTag:
    Type: String

Mappings:
  EnvMap:
    dev:
      pVpcName: dev-ai-aloe-vpc
      pOrg: ai-aloe-dev
      pNumAzs: 2
      pCreateNatGateway: true
      pCreateSingleNatGateway: true
      pCidr: 10.1.0.0/20
      pTier1Subnet1Cidr: 10.1.0.0/24
      pTier1Subnet2Cidr: 10.1.1.0/24
      pTier2Subnet1Cidr: 10.1.2.0/24
      pTier2Subnet2Cidr: 10.1.3.0/24
      pNotificationList: abragg@unicon.net
      pCreateAlarms: 'True'
    qa:
      pVpcName: qa-ai-aloe-vpc
      pOrg: ai-aloe-qa
      pNumAzs: 2
      pCreateNatGateway: true
      pCreateSingleNatGateway: true
      pCidr: 10.2.0.0/20
      pTier1Subnet1Cidr: 10.2.0.0/24
      pTier1Subnet2Cidr: 10.2.1.0/24
      pTier2Subnet1Cidr: 10.2.2.0/24
      pTier2Subnet2Cidr: 10.2.3.0/24
      pNotificationList: tcouper@1edtech.org
      pCreateAlarms: 'True'

Resources:

    Auth:
      Type: AWS::Serverless::Application
      Properties:
        Location: cognito/template.yaml
        Parameters:
          pEnv: !Ref pEnv
          SSMPrefix: !Ref AWS::StackName

    API:
      Type: AWS::Serverless::Application
      Properties:
        Location: api/template.yaml
        Parameters:
          pEnv: !Ref pEnv
          pCognitoUserPoolArn: !GetAtt Auth.Outputs.CognitoUserPoolArn
          pSensitiveDBHost: !GetAtt Backend.Outputs.SensitiveDataDatabaseEndpoint
          pSensitiveDBPort: !GetAtt Backend.Outputs.SensitiveDataDatabaseEndpointPort
          pSensitiveDBName: !GetAtt Backend.Outputs.SensitiveDataDatabaseDBName
          pSensitiveDBIamUser: !GetAtt Backend.Outputs.SensitiveDataDatabaseIamUser
          pSensitiveDBSecurityGroup: !GetAtt Backend.Outputs.SensitiveDataDatabaseSecurityGroup
          pPublishedDBHost: !GetAtt Backend.Outputs.PublishedDataDatabaseEndpoint
          pPublishedDBPort: !GetAtt Backend.Outputs.PublishedDataDatabaseEndpointPort
          pPublishedDBName: !GetAtt Backend.Outputs.PublishedDataDatabaseDBName
          pPublishedDBIamUser: !GetAtt Backend.Outputs.PublishedDataDatabaseIamUser
          pPublishedDBSecurityGroup: !GetAtt Backend.Outputs.PublishedDataDatabaseSecurityGroup
          pPrivateSubnets: !GetAtt Backend.Outputs.PrivateSubnets
          pEncryptionKey: !Ref pEncryptionKey
          pCreateAlarms: !FindInMap [EnvMap, !Ref pEnv, pCreateAlarms]
          pNotificationList: !FindInMap [EnvMap, !Ref pEnv, pNotificationList]

    Backend:
      Type: AWS::Serverless::Application
      Properties:
        Location: backend/template.yaml
        Parameters:
          pEnv: !Ref pEnv
          pVpcName: !FindInMap [EnvMap, !Ref pEnv, pVpcName]
          pOrg: !FindInMap [EnvMap, !Ref pEnv, pOrg]
          pNumAzs: !FindInMap [EnvMap, !Ref pEnv, pNumAzs]
          pCreateNatGateway: !FindInMap [EnvMap, !Ref pEnv, pCreateNatGateway]
          pCidr: !FindInMap [EnvMap, !Ref pEnv, pCidr]
          pTier1Subnet1Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier1Subnet1Cidr]
          pTier1Subnet2Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier1Subnet2Cidr]
          pTier2Subnet1Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier2Subnet1Cidr]
          pTier2Subnet2Cidr: !FindInMap [EnvMap, !Ref pEnv, pTier2Subnet2Cidr]
          pNotificationList: !FindInMap [EnvMap, !Ref pEnv, pNotificationList]
          pImageTag: !Ref pImageTag
          pCreateAlarms: !FindInMap [EnvMap, !Ref pEnv, pCreateAlarms]

Outputs:

  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt API.Outputs.AnalyticsApiEndpoint
