AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Reference API for Education Data Analytics Pipeline

  SAM Template for the API of the reference pipeline

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool
  SensitiveDBIamUser:
    Type: String
    Description: The IAM username with access to the sensitive data database
  SensitiveDBHost:
    Description: Database host name for the "sensitive" data database
    Type: String  
  SensitiveDBName:
    Description: Database Name for "sensitive" data
    Type: String  
  SensitiveDBPort:
    Description: TCP/IP Port for the "Sensitive" Database Instance
    Type: Number
    Default: 5432
  SensitiveDBSecurityGroup:
    Description: Security Group for the "Sensitive" Database Instance
    Type: String
  PublishedDBIamUser:
    Type: String
    Description: The IAM username with access to the "published" data database
  PublishedDBHost:
    Description: Database host name for the "published" data database
    Type: String  
  PublishedDBName:
    Description: Database Name for "published" data
    Type: String  
  PublishedDBPort:
    Description: TCP/IP Port for the "Published" Database Instance
    Type: Number
    Default: 5432
  PublishedDBSecurityGroup:
    Description: Security Group for the "Published" Database Instance
    Type: String
  PrivateSubnets:
    Description: Private subnets within the same VPC as the database
    Type: List<AWS::EC2::Subnet::Id>
  EncryptionKey:
    Type: String
    NoEcho: true
    Description: The encryption key for the psuedo anonymization
Resources:

  AnalyticsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Auth:
        DefaultAuthorizer: ClientCognitoAuthorizer
        Authorizers:
          ClientCognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
            AuthorizationScopes:
              - analytics/api
#      TODO: author API documentation
#      SAM will automatically generate this API documentation
#      
#      DefinitionBody:
#        Fn::Transform:
#          Name: AWS::Include
#          Parameters:
#            Location: ./openapi.yaml

#  GenerateFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: generateData.lambdaHandler
#      CodeUri: generate/
#      Runtime: nodejs20.x
#      Architectures:
#        - x86_64
#      Events:
#        EduApiData:
#          Type: Api
#          Properties:
#            RestApiId: !Ref AnalyticsApi
#            Path: /generate/{nameSpace}/{version}/{schema}
#            Method: GET
#      Environment:
#        Variables:
#          NODE_OPTIONS: --enable-source-maps
#      Layers:
#        - !Ref SchemaLayer
#      Policies:
#        - AWSLambdaBasicExecutionRole
#    Metadata: # Manage esbuild properties
#      BuildMethod: esbuild
#      BuildProperties:
#        Minify: false
#        Target: "es2020"
#        Sourcemap: true
#        EntryPoints: 
#          - generateData.ts

  # Remove this at a later date
  # just needed to verify that authentication applies to the root of the API
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs20.x
      CodeUri: src/
      Events:
        RootEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AnalyticsApi
            Path: /
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole

  EduApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: eduapi.lambdaHandler
      CodeUri: eduapi/
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref SensitiveDBSecurityGroup
        SubnetIds: !Ref PrivateSubnets
        Ipv6AllowedForDualStack: true
      Events:
        EduApiData:
          Type: Api
          Properties:
            RestApiId: !Ref AnalyticsApi
            Path: /eduapi/{version}/{schema}
            Method: POST
      Environment:
        Variables:
          AnonymizeSQSQueueUrl: !Ref AnonymizeSQSInjestQueue
          DBHost: !Ref SensitiveDBHost
          DBPort: !Ref SensitiveDBPort
          DBName: !Ref SensitiveDBName
          DBIamUser: !Ref SensitiveDBIamUser
          AwsRegion: !Ref AWS::Region
          NODE_OPTIONS: --enable-source-maps
      Layers:
        - !Ref SchemaLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: RDSConnectPolicy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/${SensitiveDBIamUser}
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnonymizeSQSInjestQueue.QueueName
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - eduapi.ts
        
  CaliperFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: caliper.lambdaHandler
      CodeUri: caliper/
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref SensitiveDBSecurityGroup
        SubnetIds: !Ref PrivateSubnets
        Ipv6AllowedForDualStack: true
      Events:
        EduApiData:
          Type: Api
          Properties:
            RestApiId: !Ref AnalyticsApi
            Path: /caliper
            Method: POST
      Environment:
        Variables:
          AnonymizeSQSQueueUrl: !Ref AnonymizeSQSInjestQueue
          DBHost: !Ref SensitiveDBHost
          DBPort: !Ref SensitiveDBPort
          DBName: !Ref SensitiveDBName
          DBIamUser: !Ref SensitiveDBIamUser
          AwsRegion: !Ref AWS::Region
          NODE_OPTIONS: --enable-source-maps
      Layers:
        - !Ref SchemaLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: RDSConnectPolicy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/${SensitiveDBIamUser}
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AnonymizeSQSInjestQueue.QueueName
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - caliper.ts

  SchemaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: schemaDocs
      ContentUri: ./json-schema
      CompatibleRuntimes:
        - nodejs20.x

  AnonymizeSQSInjestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: anonymize-sqs-injest-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AnonymizeSQSInjestDLQ.Arn
        maxReceiveCount: 5
  
  AnonymizeSQSInjestDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: anonymize-sqs-injest-dlq
      MessageRetentionPeriod: 345600  # 4 days

  AnonymizeSQSInjestEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName: !Ref AnonymizeSQSInjestFunction
      EventSourceArn: !GetAtt AnonymizeSQSInjestQueue.Arn
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 10
      Enabled: true
      ScalingConfig:
        MaximumConcurrency: 100

  AnonymizeSQSInjestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pseudoPii.handler
      CodeUri: pseudoPii/
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref PublishedDBSecurityGroup
        SubnetIds: !Ref PrivateSubnets
        Ipv6AllowedForDualStack: true
      Environment:
        Variables:
          DBHost: !Ref PublishedDBHost
          DBPort: !Ref PublishedDBPort
          DBName: !Ref PublishedDBName
          DBIamUser: !Ref PublishedDBIamUser
          AwsRegion: !Ref AWS::Region
          EncryptionKey: !Ref EncryptionKey
          NODE_OPTIONS: --enable-source-maps
      Layers:
        - !Ref SchemaLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy:
            QueueName: !GetAtt AnonymizeSQSInjestQueue.QueueName
        - Statement:
            - Sid: RDSConnectPolicy
              Effect: Allow
              Action:
                - rds-db:connect
              Resource: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:*/${PublishedDBIamUser}
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - pseudoPii.ts

Outputs:

  AnalyticsApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AnalyticsApi}.execute-api.${AWS::Region}.amazonaws.com/api"
