name: Deploy Reference Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy-pipeline-aws:
    runs-on: self-hosted
    timeout-minutes: 30
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - run: ./deploy.sh -s dev